# Generated by Django 4.2.30 on 2026-08-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mahj.models


class Migration(migrations.Migration):

    replaces = [('mahj', '0001_initial'), ('mahj', '0002_tournamentsettings_countrycourt_and_more'), ('mahj', '0003_tournamentsettings_has_teams_and_rules_default'), ('mahj', '0004_publishtarget'), ('mahj', '0005_tournamentsettings_public_url'), ('mahj', '0006_schedule_is_round'), ('mahj', '0007_welcome_plain_text'), ('mahj', '0008_draw_zero_encoding'), ('mahj', '0009_membership'), ('mahj', '0010_seed_memberships'), ('mahj', '0011_remove_player_email'), ('mahj', '0012_player_real_names'), ('mahj', '0013_drop_write_only_timestamps'), ('mahj', '0014_tenant_subdomain_unique'), ('mahj', '0015_seat_version')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('welcome', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=70)),
                ('fullname', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('period', models.CharField(default='', max_length=70)),
                ('rules', models.CharField(default='', max_length=70)),
                ('total_time', models.IntegerField(default=6900)),
                ('nb_rounds', models.IntegerField(default=7)),
                ('zoom', models.FloatField(default=1.0)),
                ('score_lines', models.IntegerField(default=20)),
                ('total_columns', models.IntegerField(default=3)),
                ('rotation_time', models.IntegerField(default=10)),
                ('counter', models.BigIntegerField(default=-1)),
                ('logo', models.BinaryField(blank=True, default=None, editable=True, null=True)),
                ('logo_etag', models.CharField(blank=True, default='', max_length=32)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('views', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('view', models.CharField(default='', max_length=70, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_refresh', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=70)),
                ('time', models.CharField(default='', max_length=70, null=True)),
                ('name', models.CharField(default='', max_length=70, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('withheld', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=70)),
                ('first_name', models.CharField(default='', max_length=70)),
                ('EMA_ID', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('team', models.CharField(blank=True, default='', max_length=70)),
                ('draw_number', models.IntegerField(blank=True, default=None, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('hand_nb', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('win_by', models.IntegerField(blank=True, default=None, null=True)),
                ('win_from', models.IntegerField(blank=True, default=None, null=True)),
                ('version', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=1.0)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CeremonyState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(default='idle', max_length=20)),
                ('step', models.IntegerField(default=0)),
                ('stat_key', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('wind', models.IntegerField(choices=[(1, 'East'), (2, 'South'), (3, 'West'), (4, 'North')])),
                ('draw_number', models.IntegerField()),
                ('minipoints', models.IntegerField(default=None, null=True)),
                ('tablepoints', models.FloatField(default=None, null=True)),
                ('penalty', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='mahj_seat_tenant__343b3f_idx'), models.Index(fields=['tenant', 'draw_number'], name='mahj_seat_tenant__8a906a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoresheet',
            constraint=models.UniqueConstraint(fields=('tenant', 'round_nb', 'table_nb'), name='unique_scoresheet_per_cell'),
        ),
        migrations.AlterUniqueTogether(
            name='publishedround',
            unique_together={('tenant', 'round_nb')},
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('tenant', 'draw_number'), name='unique_draw_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='hand',
            index=models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='mahj_hand_tenant__50ecff_idx'),
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(fields=('tenant', 'round_nb', 'table_nb', 'hand_nb'), name='unique_hand_per_cell'),
        ),
        migrations.AddConstraint(
            model_name='ceremonystate',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_ceremony_per_tenant'),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='countrycourt',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='PublishTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('host_key', models.TextField(blank=True, default='')),
                ('password_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('private_key_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='public_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='home_country',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='has_teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='rules',
            field=models.CharField(default='MCR', max_length=70),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tenant_admin', models.BooleanField(default=False)),
                ('is_scorer', models.BooleanField(default=False)),
                ('is_display_op', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mahj.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='unique_membership_per_tenant'),
        ),
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ceremonystate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='publishedround',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='last_refresh',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('subdomain',), name='unique_tenant_subdomain'),
        ),
        migrations.AddField(
            model_name='seat',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
