# Generated by Django 3.0.4 on 2022-09-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('hand_nb', models.IntegerField()),
                ('pts', models.IntegerField(default=0)),
                ('win_by', models.IntegerField(blank=True, default=None)),
                ('win_from', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=70)),
                ('first_name', models.CharField(default='', max_length=70)),
                ('EMA_ID', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='Sweden', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('rand_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('EMA_ID', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=70)),
                ('time', models.CharField(default='', max_length=70, null=True)),
                ('name', models.CharField(default='', max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('view', models.CharField(default='', max_length=70, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_refresh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('views', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('welcome', models.CharField(default='', max_length=70)),
                ('title', models.CharField(default='', max_length=70)),
                ('fullname', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('period', models.CharField(default='', max_length=70)),
                ('final', models.IntegerField(default=0)),
                ('nb_rounds', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('position', models.IntegerField()),
                ('minipoints', models.IntegerField(default=None, null=True)),
                ('tablepoints', models.FloatField(default=None, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.Player')),
            ],
        ),
    ]
