# Generated by Django 4.2.30 on 2026-07-08 14:13

from django.db import migrations, models
import django.db.models.deletion
import mahj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('welcome', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=70)),
                ('fullname', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('period', models.CharField(default='', max_length=70)),
                ('rules', models.CharField(default='', max_length=70)),
                ('total_time', models.IntegerField(default=6900)),
                ('nb_rounds', models.IntegerField(default=7)),
                ('zoom', models.FloatField(default=1.0)),
                ('score_lines', models.IntegerField(default=20)),
                ('total_columns', models.IntegerField(default=3)),
                ('rotation_time', models.IntegerField(default=10)),
                ('counter', models.BigIntegerField(default=-1)),
                ('logo', models.BinaryField(blank=True, default=None, editable=True, null=True)),
                ('logo_etag', models.CharField(blank=True, default='', max_length=32)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('views', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=70)),
                ('view', models.CharField(default='', max_length=70, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_refresh', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=70)),
                ('time', models.CharField(default='', max_length=70, null=True)),
                ('name', models.CharField(default='', max_length=70, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('withheld', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=70)),
                ('first_name', models.CharField(default='', max_length=70)),
                ('EMA_ID', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('team', models.CharField(blank=True, default='', max_length=70)),
                ('draw_number', models.IntegerField(blank=True, default=None, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('hand_nb', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('win_by', models.IntegerField(blank=True, default=None, null=True)),
                ('win_from', models.IntegerField(blank=True, default=None, null=True)),
                ('version', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=1.0)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CeremonyState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(default='idle', max_length=20)),
                ('step', models.IntegerField(default=0)),
                ('stat_key', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_nb', models.IntegerField()),
                ('table_nb', models.IntegerField()),
                ('wind', models.IntegerField(choices=[(1, 'East'), (2, 'South'), (3, 'West'), (4, 'North')])),
                ('draw_number', models.IntegerField()),
                ('minipoints', models.IntegerField(default=None, null=True)),
                ('tablepoints', models.FloatField(default=None, null=True)),
                ('penalty', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='mahj_seat_tenant__343b3f_idx'), models.Index(fields=['tenant', 'draw_number'], name='mahj_seat_tenant__8a906a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoresheet',
            constraint=models.UniqueConstraint(fields=('tenant', 'round_nb', 'table_nb'), name='unique_scoresheet_per_cell'),
        ),
        migrations.AlterUniqueTogether(
            name='publishedround',
            unique_together={('tenant', 'round_nb')},
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('tenant', 'draw_number'), name='unique_draw_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='hand',
            index=models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='mahj_hand_tenant__50ecff_idx'),
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(fields=('tenant', 'round_nb', 'table_nb', 'hand_nb'), name='unique_hand_per_cell'),
        ),
        migrations.AddConstraint(
            model_name='ceremonystate',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_ceremony_per_tenant'),
        ),
    ]
