# Generated by Django 4.2.30 on 2026-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='countrycourt',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='home_country',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
