# Generated by Django 3.0.4 on 2022-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0002_variable_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='score_lines',
            field=models.IntegerField(default=20),
        ),
    ]
