# Generated by Django 4.2.30 on 2026-07-09 10:47

from django.db import migrations, models
import django.db.models.deletion
import mahj.models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0003_tournamentsettings_has_teams_and_rules_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('host_key', models.TextField(blank=True, default='')),
                ('password_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('private_key_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
