# Generated by Django 4.2.30 on 2026-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0004_publishtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='public_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
