# Generated by Django 3.2.19 on 2024-05-04 16:08

import SOMMC2018.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0008_auto_20240504_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='player_data',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='screenmode',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='tenant',
            field=models.ForeignKey(default=SOMMC2018.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
    ]
