# Generated by Django 4.2.30 on 2026-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0009_auto_20240504_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='hand',
            index=models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='SOMMC2018_h_tenant__362ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='hand',
            index=models.Index(fields=['tenant', 'round_nb', 'table_nb', 'hand_nb'], name='SOMMC2018_h_tenant__13f531_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tenant', 'round_nb', 'table_nb'], name='SOMMC2018_p_tenant__2bec9f_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tenant', 'player'], name='SOMMC2018_p_tenant__dddd5b_idx'),
        ),
    ]
