# Generated by Django 4.2.30 on 2026-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0010_hand_version_alter_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='counter',
            field=models.IntegerField(default=-1),
        ),
    ]
