# Generated by Django 4.2.30 on 2026-07-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0010_seed_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
