# Generated by Django 4.2.30 on 2026-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0015_player_data_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
    ]
