# Generated by Django 4.2.30 on 2026-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0001_initial_squashed_0015_seat_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtarget',
            name='backup_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
