# Generated by Django 4.2.30 on 2026-06-20 12:55

from django.db import migrations, models
import django.db.models.deletion
import mahj.models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0016_hand_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(default='idle', max_length=20)),
                ('step', models.IntegerField(default=0)),
                ('stat_key', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ceremonystate',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_ceremony_per_tenant'),
        ),
    ]
