# Generated by Django 4.2.30 on 2026-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0017_ceremonystate'),
    ]

    operations = [
        # The unique constraint creates its own index on the same columns,
        # so the old non-unique 4-field index is redundant.
        migrations.RemoveIndex(
            model_name='hand',
            name='SOMMC2018_h_tenant__13f531_idx',
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'round_nb', 'table_nb', 'hand_nb'),
                name='unique_hand_per_cell'),
        ),
    ]
