# Generated by Django 4.2.30 on 2026-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0018_hand_unique_per_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
