# Generated by Django 5.2.17 on 2026-08-25 13:53

import django.core.validators
import mahj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0019_tournamentsettings_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='card_css',
            field=models.TextField(blank=True, default='', validators=[mahj.models.validate_card_css]),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='card_format',
            field=models.CharField(default='a6_portrait', max_length=16, validators=[django.core.validators.RegexValidator('^(a6_portrait|a7_landscape)$', 'Unknown card format.')]),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='card_theme',
            field=models.CharField(default='classic', max_length=16, validators=[django.core.validators.RegexValidator('^(classic|minimal|bold)$', 'Unknown card theme.')]),
        ),
    ]
