# Generated by Django 4.2.30 on 2026-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0019_position_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='total_columns',
            field=models.IntegerField(default=3),
        ),
    ]
