# Generated by Django 5.2.17 on 2026-08-27 06:15

import django.db.models.deletion
import mahj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0020_tournamentsettings_card_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('key_tail', models.CharField(blank=True, default='', max_length=8)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('last_error_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('template_img', models.BinaryField(blank=True, default=None, null=True)),
                ('template_etag', models.CharField(blank=True, default='', max_length=32)),
                ('bbox_x1', models.PositiveIntegerField(default=0)),
                ('bbox_y1', models.PositiveIntegerField(default=0)),
                ('bbox_x2', models.PositiveIntegerField(default=0)),
                ('bbox_y2', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(default=mahj.models.Tenant.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mahj.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_scan_config_per_tenant')],
            },
        ),
    ]
