# Generated by Django 5.2.17 on 2026-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahj', '0021_scanconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishtarget',
            name='backup_path',
        ),
    ]
