# Generated by Django 4.2.30 on 2026-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0021_convert_screen_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='logo',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='logo_etag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
