# Generated by Django 4.2.30 on 2026-06-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0023_variable_rotation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmode',
            name='views',
            field=models.TextField(default='Unknown'),
        ),
    ]
