# Generated by Django 4.2.30 on 2026-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0024_alter_screenmode_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='welcome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
