# Generated by Django 3.0.4 on 2022-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='zoom',
            field=models.FloatField(default=1.0),
        ),
    ]
