# Generated by Django 3.0.4 on 2022-09-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0003_variable_score_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_data',
            name='first_name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
