# Generated by Django 3.0.4 on 2022-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0004_player_data_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='total_time',
            field=models.IntegerField(default=6900),
        ),
    ]
