# Generated by Django 3.0.4 on 2022-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0005_variable_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='rules',
            field=models.CharField(default='', max_length=70),
        ),
    ]
