# Generated by Django 3.2.19 on 2024-05-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0007_tenant_tenantawaremodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='subdomain_prefix',
            new_name='subdomain',
        ),
        migrations.AddField(
            model_name='hand',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='player',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='player_data',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='screen',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='screenmode',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.AddField(
            model_name='variable',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOMMC2018.tenant'),
        ),
        migrations.DeleteModel(
            name='TenantAwareModel',
        ),
    ]
