# Generated by Django 4.2.30 on 2026-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0013_publishedround'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
