# Generated by Django 4.2.30 on 2026-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOMMC2018', '0014_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_data',
            name='team',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
